In [1]:
import os
import ringity
import numpy as np
import networkx as nx

In [2]:
RINGITY_PATH = os.path.dirname(ringity.__file__)

In [3]:
G = nx.erdos_renyi_graph(2**11, 0.05)

In [4]:
L = nx.laplacian_matrix(G).toarray()
C = np.zeros(L.shape)
C[1:,1:] = np.linalg.inv(L[1:,1:])
    
N = G.number_of_nodes()
E = G.number_of_edges()
B = nx.incidence_matrix(G, oriented=True)
F = (C@B).T

In [38]:
np.sum(np.abs(F - (B.T).dot(C)))

8.773533635708652e-10

In [40]:
%%timeit
(B.T).dot(C)

1.35 s ± 32.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [41]:
%%timeit
(C@B).T

1.42 s ± 58.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [39]:
np.count_nonzero(F), F.size

(214761005, 214865920)

In [42]:
nx.laplacian_matrix(G1).toarray()

array([[8, 0, 0, ..., 0, 0, 0],
       [0, 3, 0, ..., 0, 0, 0],
       [0, 0, 6, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 5, 0, 0],
       [0, 0, 0, ..., 0, 9, 0],
       [0, 0, 0, ..., 0, 0, 3]], dtype=int64)

In [43]:
nx.laplacian_matrix(G2).toarray()

array([[64, -1, -1, ...,  0,  0,  0],
       [-1, 46, -1, ...,  0,  0,  0],
       [-1, -1, 51, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  2,  0,  0],
       [ 0,  0,  0, ...,  0,  1,  0],
       [ 0,  0,  0, ...,  0,  0,  0]], dtype=int64)

In [7]:
G = nx.Graph()
G.add_nodes_from([0])

In [8]:
ringity.centralities.net_flow(G)

{}

In [33]:
nx.adjacency_matrix(G2).toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [38]:
? nx.laplacianmatrix.not_implemented_for

In [31]:
G = nx.erdos_renyi_graph(2**8, 0.05)

In [32]:
D = nx.floyd_warshall_numpy(G)

In [41]:
D2 = nx.shortest_path_length(G, method='bellman-ford')

In [24]:
D2

<generator object all_pairs_shortest_path_length at 0x12355db88>

In [26]:
? nx.all_shortest_paths